### ISSUE TITLE
Disegnare la struttura del sito

### ISSUE THREAD

**Issue by EnricoMiccoli** [ProCicerone/ProCicerone.github.io#1]
Lavoro per @KoraMontemagno, con i suoi appunti e con la tabella morabitiana

**Comment by KoraMontemagno** [comment]
## Materiali che servono per l'ipertesto:

### Date delle principali orazioni
- 81 Prima causa; 
- 80 Pro Roscio Armerino; 
- 70 Verrine;
- 66 Pro Lege Manilia; 
- 63 Catilinarie, Pro Murena; 
- 62 Pro Archia; 
- 56 Pro Sestio, Pro Caelio, De provinciis consulatibus;
- 52 Pro Milone;
-  44 Filippiche

### Date e momenti della vita di cicerone
- 106 nascita ad Arpino; 
  primi studi a Roma; 
- 79-77 Viaggio in Grecia; 
- 75 Questura in Sicilia; 
- 66 Pretura; 63 Consolato; 
- 58 Esilio; 
- 57 Ritorno a Roma

Date di vita e di orazioni sono da mettere in parallelo

### Associare ad ogni orazione le sue peculiarità, che qui schematizzo:

Pro Roscio: difesa di Roscio Armerino accusato di parricidio con false prove per essere eliminato da Silla. Orazione giudiziaria con stile che si rifa all'asianesimo
Verrine: orazione giudiziaria contro verre (cicerone era stato richiamato dai siciliani per loro difesa dai sprusi del governatore). Si articola in 5 orazioni, ma dopo la DIvinatio in caecilium e la prima verrina il reus fugge per l'abbondanza di prove e viene condannato in contumacia. Stile bilanciato tra asianesimo e atticismo, inizia ad essere quello tipico ciceroniano.
Pro lege manilia: orazione deliberativa per approvare poteri speciali a Pompeo per condurre la campagna contro Mitridate re del Ponto. Il provvedimento avrebbe favorito il progetto ciceroniano della concordia ordinum, secondo il quale aristocrazia e ceto equestre avrebbero dovuto collaborare per fronteggiare la crisi della repubblica.
Catilinarie: orazione giudiziaria dove cicerone prende le parti dell'actor (oltre che console) pper condannare Catilina e i cospiratori
Pro Murena: difesa di murena condannato da Catone l'Uticense per la dissolutezza di costumi. Presenta un nuovo modello etico, meno rigido della mos maiorum catoniana
Pro Archia: difesa del poeta Archio, accusato di aver usurpato la cittadinanza romana. Si trasforma in una difesa della poesia
Pro sestio: nuovo progetto politico: consensus omnium bonorum non bastano due ceti sociali, ma tutti i boni possono contribuire alla realizzazione di un progetto politico
Pro Caelio: difesa di Celio, accusato di aver offeso Clodia; si trasforma in un'orazione contro Clodio, che lo aveva esiliato.
Pro Milone: migliore orazione scritta da cicerone in difesa di un amico, mai pronunciata per via del clima in tribunale
Filippiche: orazioni contro antonio, riprese da quelle contro Filippo di macedonia prounciate e scritte da Demostene

A stasera caratteristiche dell'oratoria e trattati

**Comment by EnricoMiccoli** [comment]
@KoraMontemagno  descrivi anche la struttura dell'informazione, per il momento i contenuti sono secondari.

**Comment by KoraMontemagno** [comment]
Come struttura si potrebbe fare un incipit per una breve descrizione del personaggio di cicerone (rapporto con la politica, ambiguità della personalità), iniziare parallelamente con le date di vita e di orazioni e associare ogni orazione al suo contenuto. Quelle che abbiamo fatto (Pro Sestio T14, Pro Caelio T7, Pro murena T12, Verrine T1 T3) e le altre che faremo dovrebbero essere correlate ciascuna alla sua corrispettiva, con testo latino, traduzione e note (per esempio figure retoriche).
Segue poi tutto un paragrafo dove si delineano le tipologie di orazione e lo stile, un altro che riguarda la parte trattatistica di cicerone, con infine il de oratore (e quindi lo schema dei contenuti) correlato con tanto di file della morabito (retorica maior e minor)
Alla fine di tutto potremmo fare un riassunto delle orazioni lette in italiano (qui potremmo aggiungere immagini, ce ne sono della congiura di catilina)
