### ISSUE TITLE
Non vengono caricati i css della timeline

### ISSUE THREAD

**Issue by KoraMontemagno** [ProCicerone/ProCicerone.github.io#15]

**Comment by EnricoMiccoli** [comment]
@KoraMontemagno  ha editato una versione precedente al commit 755086b69ffe51cd3fdf38c622ce596284910e0a, vecchia di 6 giorni, quindi i nomi delle classi sono errati.

Farò un `revert`, poi sarà rieditato timeline. 

Reverted in 77550ce7938900796d200809826afff41269c0a9
