### ISSUE TITLE
Preparare elenco di figure retoriche

### ISSUE THREAD

**Issue by EnricoMiccoli** [ProCicerone/ProCicerone.github.io#20]
Sto implementando note  piè di pagina interattive, a breve caricheremo le versioni con le note, quindi è necessario prepararle da adesso per poterle aggiungere dopo.

**Comment by KoraMontemagno** [comment]
Come la annoto? [Sintagmi]= figura?

**Comment by EnricoMiccoli** [comment]
Per il momento scrivilo come vuoi e tienilo te, così quando ci sarà la struttura finalizzata potrai riempirla velocemente.
