### ISSUE TITLE
Cercare immagini di approfondimento

### ISSUE THREAD

**Issue by EnricoMiccoli** [ProCicerone/ProCicerone.github.io#27]

**Comment by KoraMontemagno** [comment]
http://1.bp.blogspot.com/-qMTjlapypJw/T8jIX9dHpYI/AAAAAAAAJZI/ybhyX07fGvY/s1600/marco-antonio.jpg
marco antonio

http://www.laltrapagina.it/mag/wp-content/uploads/2014/03/cicerone.jpg
cicerone

https://upload.wikimedia.org/wikipedia/commons/a/a3/Maccari-Cicero.jpg
cicerone in senato, durante il processo contro Catilina

http://valparadiso.altervista.org/blog/wp-content/uploads/2012/12/verre.jpg
verre

http://1.bp.blogspot.com/-3CqhTUYU76s/VJBHruly4MI/AAAAAAAAWSE/FVMzittI3ZU/s1600/pompeo.jpg
pompeo

http://www.ristorante-laperla.it/wp-content/uploads/2014/05/Veduta-Arpino.jpg
Arpino

https://upload.wikimedia.org/wikipedia/commons/7/72/Sir_Edward_John_Poynter_lesbia_and_her_sparrow.jpg
clodia

**Comment by KoraMontemagno** [comment]
@EnricoMiccoli dove e come le mettiamo?

**Comment by EnricoMiccoli** [comment]
Sono di approfondimento alle versioni? @Arkanod voleva metterle nelle note. Potremmo metterle a lato delle traduzioni o delle spiegazioni.

**Comment by KoraMontemagno** [comment]
Sono un po' a caso, generalmente spiegano i personaggi. Accanto alle versioni va bene, ma conta che alcune  (tipo marco antonio o arpino) si riferiscono alle didascalie della timeline

**Comment by EnricoMiccoli** [comment]
Ci rinuncio.
